# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-07 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190803_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keyword',
            field=models.ManyToManyField(default='', to='blog.Keyword', verbose_name='关键字'),
        ),
    ]
