# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-07 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_keyword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['id'], 'verbose_name': '关键词', 'verbose_name_plural': '关键词'},
        ),
    ]
