# Generated by Django 2.2.5 on 2020-07-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200704_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(default='', verbose_name='文章内容'),
        ),
    ]
