# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-07 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190807_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='keyword',
            field=models.ManyToManyField(blank=True, default='', to='blog.Keyword', verbose_name='关键字'),
        ),
    ]
