# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-07 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190807_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='keyword',
        ),
    ]
