# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-07 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190807_1030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notices',
            new_name='Notice',
        ),
    ]
