# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-07 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190807_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='text',
            field=models.TextField(default='', null=True, verbose_name='公告'),
        ),
    ]
