# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-07 18:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_articlecategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间'),
        ),
    ]
