# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-09-02 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_article_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='文章简介'),
        ),
    ]
