# Generated by Django 2.2.3 on 2019-09-12 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190902_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.ArticleCategory', verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='bigCategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.BigCategory', verbose_name='大分类'),
        ),
    ]
