# Generated by Django 2.2.5 on 2020-06-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200413_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='gender',
            field=models.CharField(choices=[('female', '女'), ('male', '男')], default='男', max_length=5),
        ),
    ]
