# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-25 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190725_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='name',
            field=models.CharField(default='', max_length=10, verbose_name='昵称'),
        ),
    ]
