# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-25 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190725_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpro',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/', verbose_name='用户图像'),
        ),
    ]
