# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-03 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20190802_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='email',
            field=models.EmailField(default='', max_length=20, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userpro',
            name='gender',
            field=models.CharField(choices=[('female', '女'), ('male', '男')], default='男', max_length=5),
        ),
    ]
