# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-06 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_emailverifyrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpro',
            name='name',
        ),
        migrations.AddField(
            model_name='userpro',
            name='nick_name',
            field=models.CharField(default='', max_length=10, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userpro',
            name='gender',
            field=models.CharField(choices=[('female', '女'), ('male', '男')], default='男', max_length=5),
        ),
    ]
