# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-06 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20190806_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=5),
        ),
        migrations.AlterField(
            model_name='userpro',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='昵称'),
        ),
    ]
