# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-07 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20190807_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='gender',
            field=models.CharField(choices=[('female', '女'), ('male', '男')], default='male', max_length=5),
        ),
    ]
