# Generated by Django 2.2.3 on 2019-09-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20190902_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
